name: r-sc
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
dependencies:
  - r-base>=4.3,<4.5
  - r-seurat>=5,<6
  - r-seuratobject>=5,<6
  - r-matrix>=1.6,<2
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-ggplot2
  - r-patchwork
  - r-future
  - r-future.apply
  - r-harmony
  - r-remotes
  - r-biocmanager
  - r-hdf5r
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-edger
  - bioconductor-limma
